version: '3.8'

services:
  bot:
    build: .
    container_name: foosball_bot
    environment:
      - DATABASE_PATH=${DATABASE_PATH}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./foosball.db:/app/foosball.db  # Persist SQLite database to the host machine
    restart: unless-stopped
